### PR TITLE
Make settings configurable

### PR DESCRIPTION
**Pull request by nvcexploder**
This adds the ability to use the default settings file ('./settings'), or specify settings via a command line option, or via an environment variable. Details are explained in the README.

### CODE REVIEW

**Comment by nvcexploder** [comment]
Closes #9

**Comment by RichardLitt** [comment]
I don't think that we should use the settings file. Or, if we do, we should change it so that the station is more generic. Right now, it'll always default to logging things at my house. Perhaps we should simply remove the locations? Or change one to be in the middle of North America or something.

**Comment by nvcexploder** [comment]
sure - I think that's fine. I also think it can be in a subsequent PR, removing your personal settings from the example, or creating a new ./settings.json, and moving the existing to ./richardlitt.json or something similar.

**Comment by RichardLitt** [comment]
I also tend to use standard linter. That should be added to the npm manifest, maybe?

**Comment by nvcexploder** [comment]
I'll add that in.

**Comment by RichardLitt** [comment]
Looks good to me!

**Pull request merged**
